### ISSUE TITLE
number formatter에서 숫자 키패드의  '.'  입력안되는 현상.

### ISSUE THREAD

**Issue by ZZINY** [ax5ui/ax5ui-formatter#1]
안녕하세요?
숫자 포맷터에서 숫자키패드의 '.' 는 입력이 안되고  있습니다.
예제 : http://ax5.io/ax5ui-formatter/demo/index.html

src/modules/ax5formatter-formatter.js 파일 : 87  라인
'190': '.','110':'.' 로 변경해주시기 바랍니다.

일부러 빼셨다면 다시 재정의하여 사용하겠습니다.
답변바랍니다.
감사합니다.

**Comment by aeei** [comment]
변경하였습니다. 최신버전의 ax5ui-formatter를 내려받아 사용해보세요.
ax5ui 스타도 눌러주시면 감사하겠습니다!

**Comment by thomasJang** [comment]
@ZZINY 님 요즘 ax5ui 로 개발하시는 것 같은데요. 저희 레포지터리들에 "Star" 좀 눌러주세요.
그래야 오픈소스가 지속적으로 개발될 수 있습니다.

**Comment by ZZINY** [comment]
넹~ Star 클릭클릭 !!
